global:
  slack_api_url: 'https://hooks.slack.com/services/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'

route:
  receiver: 'slack-notifications'

receivers:
- name: 'slack-notifications'
  slack_configs:
  - channel: '#natalia_konyaeva'
